# Generated by Django 6.1.1 on 2026-09-21 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('estimated_age', models.PositiveSmallIntegerField(blank=True, help_text='Estimated age in years.', null=True)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('identifying_features', models.TextField(blank=True, help_text='Distinctive physical characteristics.')),
                ('vaccination_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('UNVACCINATED', 'Unvaccinated'), ('VACCINATED', 'Vaccinated')], default='UNKNOWN', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
