# Generated by Django 6.1.1 on 2026-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.AlterField(
            model_name='dog',
            name='estimated_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated age in months.', null=True),
        ),
    ]
