# Generated by Django 6.1.1 on 2026-09-21 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('REPORT_CREATED', 'Report Created'), ('REPORT_UPDATED', 'Report Updated'), ('CASE_ASSIGNED', 'Case Assigned'), ('VACCINATION_SUBMITTED', 'Vaccination Submitted'), ('VERIFICATION_STARTED', 'Verification Started'), ('VERIFICATION_COMPLETED', 'Verification Completed'), ('VERIFICATION_FLAGGED', 'Verification Flagged'), ('STATUS_CHANGED', 'Status Changed'), ('COMMENT_ADDED', 'Comment Added')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reports.dogreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
