# Generated by Django 6.1.1 on 2026-09-21 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dog_match_score', models.FloatField(blank=True, help_text='Similarity score between the original and evidence dog images.', null=True)),
                ('image_integrity_score', models.FloatField(blank=True, help_text='Estimated image integrity score.', null=True)),
                ('image_integrity', models.CharField(choices=[('PENDING', 'Pending'), ('PASS', 'Pass'), ('SUSPICIOUS', 'Suspicious'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('metadata_consistent', models.BooleanField(blank=True, null=True)),
                ('duplicate_detected', models.BooleanField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged'), ('REVIEW', 'Requires Review'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, help_text='Human-readable explanation of the verification result.')),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('vaccination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='vaccinations.vaccinationrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['decision'], name='verificatio_decisio_0985b2_idx'), models.Index(fields=['created_at'], name='verificatio_created_0bf44d_idx')],
            },
        ),
    ]
