# Generated by Django 6.1.1 on 2026-09-21 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_type', models.CharField(choices=[('RABIES', 'Rabies'), ('OTHER', 'Other')], default='RABIES', max_length=20)),
                ('vaccine_name', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('evidence_image', models.ImageField(upload_to='vaccinations/evidence/')),
                ('administered_at', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_VERIFICATION', 'Under Verification'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_administered', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dogs.dog')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination', to='reports.dogreport')),
            ],
            options={
                'ordering': ['-administered_at'],
                'indexes': [models.Index(fields=['status'], name='vaccination_status_f75cbe_idx'), models.Index(fields=['administered_at'], name='vaccination_adminis_91d78a_idx')],
            },
        ),
    ]
