# Generated by Django 6.1.1 on 2026-09-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='administered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='VaccinationAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_detected', models.BooleanField(default=False)),
                ('ear_tag_detected', models.BooleanField(default=False)),
                ('ear_tag_number', models.CharField(blank=True, max_length=100)),
                ('ear_tag_readable', models.BooleanField(default=False)),
                ('image_quality', models.CharField(blank=True, max_length=20)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vaccination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='vaccinations.vaccinationrecord')),
            ],
        ),
    ]
